---
title: "Problem Sets"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message=FALSE, warning = FALSE, eval = TRUE, 
  fig.width = 16/2, fig.height = 9/2
)

# Set seed value of random number generator to get "replicable" random numbers.
# Why 76? Because of https://www.youtube.com/watch?v=xjJ7FheCkCU
set.seed(76)
```

<!--
{target="_blank"}
-->

<style>
h1{font-weight: 400;}
</style>


Dr. Jenny Smetzer and Albert Y. Kim (Smith College) have produced lab materials and problem sets for ModernDive.

The solutions for all lab materials are available to verified instructors by filling out this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSf68Je_Q3ggRJ-74UtL0xG5-IuuKkSTIpEQZWro-8QbO7nmdA/viewform){target="_blank"}.



***



# PS01 Introduction to R

Featuring:

* A [problem set](static/PS01 - intro to R/PS01_source.html){target="_blank"} on an introduction to R and RStudio.

Download all necessary files: <a href="static/PS01 - intro to R/PS01.zip" download>`PS01.zip`</a>


***



# PS02: Data visualization with `ggplot2`

Featuring:

* A short [pre-lecture](static/PS02 - data visualization/pre_lecture.pdf){target="_blank"} explaning the Grammar of Graphics as implemented in the `ggplot2` package.
* A [problem set](static/PS02 - data visualization/PS02_data_viz.html){target="_blank"} on data visualization

Download all necessary files: <a href="static/PS02 - data visualization/PS02.zip" download>`PS02.zip`</a>



***



# PS03: Data wrangling with `dplyr`

Featuring:

* A short [pre-lecture](static/PS03 - data wrangling/pre_lecture.pdf){target="_blank"} explaning the `%>%` operator and `dplyr` wrangling verbs.
* A [problem set](static/PS03 - data wrangling/PS03_data_wrangling_source.html){target="_blank"} on data visualization

Download all necessary files: <a href="static/PS03 - data wrangling/PS03.zip" download>`PS03.zip`</a>



***



# PS04: Regression with one numerical variable

Featuring:

* A [problem set](static/PS04 - simple linear regression/PS04_lastname_firstname.html){target="_blank"} on 

Download all necessary files: <a href="static/PS04 - simple linear regression/PS04.zip" download>`PS04.zip`</a>



***




# PS05: Regression with one categorical variable

Featuring:

* A [problem set](static/PS05 - regression with one cat x/PS05_firstname_lastname.html){target="_blank"} on

Download all necessary files: <a href="static/PS05 - regression with one cat x/PS05.zip" download>`PS05.zip`</a>





***



# PS06: Regression with one numerical and one categorical variable

Featuring:

* A [problem set](static/PS06 - reg with one cat one numeric/PS06_firstname_lastname.html){target="_blank"} on

Download all necessary files: <a href="static/PS06 - reg with one cat one numeric/PS06.zip" download>`PS06.zip`</a>



***



# PS07: Sampling distributions

Featuring:

* A [recap](static/PS07 - sampling distributions/sampling_dist_recap.html){target="_blank"} on the effect of sample size on sampling distributions.
* A [problem set](static/PS07 - sampling distributions/PS07_firstname_lastname.html){target="_blank"} on

Download all necessary files: <a href="static/PS07 - sampling distributions/PS07.zip" download>`PS07.zip`</a>




***



# PS08: Confidence intervals and the bootstrap

Featuring:

* A [problem set](static/PS08 - confidence intervals/PS08_firstname_lastname.html){target="_blank"} on

Download all necessary files: <a href="static/PS08 - confidence intervals/PS08.zip" download>`PS08.zip`</a>



***



# PS09: Hypothesis testing

Featuring:

* A [problem set](static/PS09 - hypothesis testing/PS09_firstname_lastname.html){target="_blank"} on

Download all necessary files: <a href="static/PS09 - hypothesis testing/PS09.zip" download>`PS09.zip`</a>



***



# PS10: Inference for regression

We don't have one yet! If you would like to contribute one, please let us know.
